name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v2

      - name: Install system dependencies for Computron
        run: sudo apt update && sudo apt install libxml2-dev libxslt1-dev

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Computron and launch tests
        run: npm install -g node-gyp && npm install && npm test
